// Generated by MiMo V2.5 Free via OpenCode.

import { useState, useEffect, useCallback, useRef } from "react";
import nekoSprite from "./neko.png";

const SPRITE_SIZE = 32;
const SCALE = 2;
const COLS = 4;

const SLEEP_SPRITES = [7, 8, 9];
const WAKE_SPRITES = [11, 1, 2, 3, 4, 5];
const PET_SPRITES = [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6];

const SLEEP_FRAME_MS = 500;
const WAKE_FRAME_MS = 300;
const PET_FRAME_MS = 300;

function spritePosition(spriteNum: number) {
  const col = (spriteNum - 1) % COLS;
  const row = Math.floor((spriteNum - 1) / COLS);
  return { x: -(col * SPRITE_SIZE * SCALE), y: -(row * SPRITE_SIZE * SCALE) };
}

type State = "sleep" | "waking" | "petting";

export default function Neko() {
  const [state, setState] = useState<State>("sleep");
  const [spriteNum, setSpriteNum] = useState(SLEEP_SPRITES[0]);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const clearTimer = useCallback(() => {
    if (timerRef.current !== null) {
      clearTimeout(timerRef.current);
      timerRef.current = null;
    }
  }, []);

  useEffect(() => {
    clearTimer();

    if (state === "sleep") {
      let idx = 0;
      const tick = () => {
        idx = (idx + 1) % SLEEP_SPRITES.length;
        setSpriteNum(SLEEP_SPRITES[idx]);
        timerRef.current = setTimeout(tick, SLEEP_FRAME_MS);
      };
      timerRef.current = setTimeout(tick, SLEEP_FRAME_MS);
    } else if (state === "waking") {
      let idx = 0;
      setSpriteNum(WAKE_SPRITES[0]);
      const tick = () => {
        idx++;
        if (idx >= WAKE_SPRITES.length) {
          setState("petting");
          return;
        }
        setSpriteNum(WAKE_SPRITES[idx]);
        timerRef.current = setTimeout(tick, WAKE_FRAME_MS);
      };
      timerRef.current = setTimeout(tick, WAKE_FRAME_MS);
    } else if (state === "petting") {
      let idx = 0;
      setSpriteNum(PET_SPRITES[0]);
      const tick = () => {
        idx++;
        if (idx >= PET_SPRITES.length) {
          setState("sleep");
          return;
        }
        setSpriteNum(PET_SPRITES[idx]);
        timerRef.current = setTimeout(tick, PET_FRAME_MS);
      };
      timerRef.current = setTimeout(tick, PET_FRAME_MS);
    }

    return clearTimer;
  }, [state, clearTimer]);

  const handleClick = useCallback(() => {
    if (state === "sleep") {
      setState("waking");
    }
  }, [state]);

  const pos = spritePosition(spriteNum);

  return (
    <>
      <style>{`
        @media (prefers-color-scheme: dark) {
          .neko-sprite {
            filter: drop-shadow(0 0 1px #fff) drop-shadow(0 0 1px #fff);
          }
        }
      `}</style>
      <button
        type="button"
        className="neko-sprite"
        aria-label="Neko cat"
        disabled={state !== "sleep"}
        onClick={handleClick}
        style={{
          width: SPRITE_SIZE * SCALE,
          height: SPRITE_SIZE * SCALE,
          border: "none",
          padding: 0,
          background: "transparent",
          backgroundImage: `url(${nekoSprite.src})`,
          backgroundPosition: `${pos.x}px ${pos.y}px`,
          backgroundRepeat: "no-repeat",
          backgroundSize: `${SPRITE_SIZE * 4 * SCALE}px ${SPRITE_SIZE * 3 * SCALE}px`,
          imageRendering: "pixelated",
          cursor: state === "sleep" ? "pointer" : "default",
        }}
      />
    </>
  );
}
